#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr

bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap           6
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a URxvt:cmus state=floating rectangle=600x250+0+0 center=true
bspc rule -a URxvt:iwd state=floating rectangle=520x200+0+0 center=true
bspc rule -a Firefox-esr desktop='^5' follow=on
bspc rule -a mpv state=floating desktop='^5' follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# kill
pkill picom
pkill lxpolkit

# picom
picom -b &

# autenthic
lxpolkit &

# setup
$HOME/.config/bspwm/scripts/startup.sh &
